# Generated by Django 4.2 on 2023-06-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
