# Generated by Django 4.2 on 2023-06-27 18:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('productManagement', '0002_sale_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
